/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zkVerifiableCredentialsDbCoreVerifierSol from "./zkVerifiableCredentialsDBCoreVerifier.sol";
export type { zkVerifiableCredentialsDbCoreVerifierSol };
export type { CredentialsDB } from "./CredentialsDB";
//export type { Lock } from "./Lock"; // COMMENTED BY GB
