/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as zkVerifiableCredentialsDbCoreVerifierSol from "./zkVerifiableCredentialsDBCoreVerifier.sol";
export { CredentialsDB__factory } from "./CredentialsDB__factory";
